apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-cm
  namespace: mosquitto-app-anonymous
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    listener 1883
    allow_anonymous true
